#!/bin/sh
set -e -x

# Add group
addgroup -S tomcat

# Add user
adduser -D -G tomcat -S tomcat

# Adding curl
apk add --no-cache curl

# Downloading confd
curl -L --retry 5 -o /usr/local/bin/confd \
  https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64
chmod +x /usr/local/bin/confd

# Creating confd config directory
mkdir -p /etc/confd/conf.d
mkdir -p /etc/confd/templates

# Moving templates in place
cp /resources/confd/templates/* /etc/confd/templates/
# Moving config in place
cp /resources/confd/conf.d/* /etc/confd/conf.d/

chown -R tomcat:tomcat /etc/confd

# Downloading pinpoint agent
curl -L -o /resources/pinpoint.tar.gz \
  https://github.com/naver/pinpoint/releases/download/${PINPOINTAGENT_VERSION}/pinpoint-agent-${PINPOINTAGENT_VERSION}.tar.gz

# Creating some dir
mkdir -p /opt/pinpoint/pinpoint-agent

# Unzipping tar
tar -xz -C /opt/pinpoint/pinpoint-agent -f /resources/pinpoint.tar.gz

# Changing permissions on pinpoint-agent
chown -R tomcat:tomcat /opt/pinpoint

# Setup entrypoint
mv /resources/entrypoint.sh /entrypoint.sh

# Moving setenv.sh into place
mv /resources/setenv.sh ${CATALINA_HOME}/bin/setenv.sh
